[package]
name = "serieusb"
version = "0.1.0"
edition = "2021"
authors = ["Marc-Antoine Manningham", "Charles Khouzry"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.9.1"
anyhow = "1.0.69"
clap = {version = "4.1.4", features = ["derive"] }
derive_more = "0.99.17"
ctrlc = "3.2.5"
indicatif = "0.17.3"